# Site settings

title: The Storyograph
email: Nils-Peter@The-Storyograph.com
description1: "Travel & Portrait & Wedding"

# Build settings

markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
