#-------------------------------
# General Site Settings

title: The Storyograph
email: Nils-Peter@The-Storyograph.com
description: "Because a picture is worth a thousand words."


# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: The Story, url: '#theStory'}
- {name: Portfolio, url: '#portfolio'}
- {name: Pricing, url: '#pricing'}
- {name: Print, url: '#print'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Travel & Landscape, Portrait and Wedding. Hier findet ihr Bilder die Geschichten erzählen. Lasst mich auch euere Geschichte erzählen. Egal ob Portrait oder Hochzeit im Raum Braunschweig oder International. Ich freue mich auf euch! Because a picture is worth a thousand words.'
  rel-author: 'https://www.the-storyograph.com'
  rel-publisher: 'https://www.the-storyograph.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-96378888-1


#-------------------------------
# Portfolio Section

portfolio:
- {name: Travel & Landscape, folder: 'travel_and_landscape', file: 'portfolio/tra_and_lan.html'}
- {name: Portrait, folder: 'portrait', file: 'portfolio/portrait.html'}
- {name: Wedding, folder: 'wedding', file: 'portfolio/wedding.html'}

#-------------------------------
# Clients Section

pricing:
- {name: Wedding, folder: 'wedding', file: 'pricing/wedding.html'}
- {name: Portrait, folder: 'portrait', file: 'pricing/portrait.html'}
- {name: Travel, folder: 'travel', file: 'pricing/travel.html'}
- {name: Event, folder: 'event', file: 'pricing/event.html'}


